function HWK4MarsPressuredataSLE031124 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  HWK4MARSPRESSUREDATASLE031124 = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  HWK4MARSPRESSUREDATASLE031124 = IMPORTFILE(FILE, SHEET) reads from
%  the specified worksheet.
%
%  HWK4MARSPRESSUREDATASLE031124 = IMPORTFILE(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  HWK4MarsPressuredataSLE031124 = importfile("C:\Users\spencer.freeman\Desktop\projects\school\upper-atmosphere\hw4\HWK4_Mars_Pressure_data_SLE_031124.xlsx", "Sheet1", [1, 8877]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Mar-2024 22:49:39

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 8877];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Import the data
HWK4MarsPressuredataSLE031124 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    HWK4MarsPressuredataSLE031124 = [HWK4MarsPressuredataSLE031124; tb]; %#ok<AGROW>
end

end