function Homework1inputSLE012224 = importfile2(workbookFile, sheetName, dataLines)
    %IMPORTFILE Import data from a spreadsheet
    %  HOMEWORK1INPUTSLE012224 = IMPORTFILE(FILE) reads data from the first
    %  worksheet in the Microsoft Excel spreadsheet file named FILE. 
    %  Returns the data as a cell array.
    %  
    %  HOMEWORK1INPUTSLE012224 = IMPORTFILE(FILE, SHEET) reads from the
    %  specified worksheet.
    %  
    %  HOMEWORK1INPUTSLE012224 = IMPORTFILE(FILE, SHEET, DATALINES) reads
    %  from the specified worksheet for the specified row interval(s).
    %  Specify DATALINES as a positive scalar integer or a N-by-2 array of
    %  positive scalar integers for dis-contiguous row intervals.
    %  
    %  Example:
    %  Homework1inputSLE012224 = importfile("C:\Users\spenc\Desktop\school shit 2\Spring_2024\upper_atmosphere\Homework_1_input_SLE_012224.xlsx", "Input", [2, Inf]);
    %  
    %  See also READTABLE.
    %  
% Auto-generated by MATLAB on 31-Jan-2024 20:41:41

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "EffectiveRadiusM", "VarName9", "VarName10", "massKg"];
opts.SelectedVariableNames = ["EffectiveRadiusM", "VarName9", "VarName10", "massKg"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "EffectiveRadiusM", "VarName9", "VarName10", "massKg"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "EffectiveRadiusM", "VarName9", "VarName10", "massKg"], "EmptyFieldRule", "auto");

% Import the data
Homework1inputSLE012224 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
opts.DataRange = dataLines(idx, :);
tb = readtable(workbookFile, opts, "UseExcel", false);
Homework1inputSLE012224 = [Homework1inputSLE012224; tb]; %#ok<AGROW>
end

%% Convert to output type
Homework1inputSLE012224 = table2cell(Homework1inputSLE012224);
numIdx = cellfun(@(x) ~isnan(str2double(x)), Homework1inputSLE012224);
Homework1inputSLE012224(numIdx) = cellfun(@(x) {str2double(x)}, Homework1inputSLE012224(numIdx));
end